export interface SyllabusTopic {
  subject: string;
  topics: string[];
}

export const JHS_SYLLABUS: SyllabusTopic[] = [
  {
    subject: "Mathematics",
    topics: [
      "Number and Numeration",
      "Fractions, Decimals and Percentages",
      "Ratio and Proportion",
      "Integers and Real Numbers",
      "Algebraic Expressions",
      "Linear Equations and Inequalities",
      "Geometry and Shapes",
      "Measurement (Perimeter, Area, Volume)",
      "Statistics and Data Handling",
      "Probability",
      "Sets",
      "Number Bases",
    ],
  },
  {
    subject: "English Language",
    topics: [
      "Comprehension and Summary",
      "Vocabulary Development",
      "Parts of Speech (Nouns, Verbs, Adjectives, Adverbs)",
      "Tenses and Subject-Verb Agreement",
      "Sentence Construction and Types",
      "Punctuation and Spelling",
      "Essay Writing (Narrative, Descriptive, Argumentative)",
      "Letter Writing (Formal and Informal)",
      "Idioms and Figurative Language",
      "Direct and Indirect Speech",
    ],
  },
  {
    subject: "Integrated Science",
    topics: [
      "Diversity of Living Things",
      "Life Processes (Nutrition, Respiration, Reproduction)",
      "Ecology and the Environment",
      "The Human Body Systems",
      "Matter and Its Properties",
      "Mixtures and Compounds",
      "Forces and Energy",
      "Electricity and Magnetism",
      "The Solar System",
      "Soil and Water Conservation",
    ],
  },
  {
    subject: "Social Studies",
    topics: [
      "The Family and the Community",
      "Ghana's Independence and Government",
      "The Constitution and Human Rights",
      "Culture and National Identity",
      "Population and Migration",
      "Environmental Issues and Conservation",
      "Economic Activities in Ghana",
      "Science and Technology in Development",
      "Conflict Resolution",
      "Youth and National Development",
    ],
  },
  {
    subject: "ICT",
    topics: [
      "Introduction to Computers",
      "Computer Hardware and Software",
      "Word Processing",
      "Spreadsheets",
      "Internet and Email",
      "Computer Networks",
      "Data Management",
      "Desktop Publishing",
      "Health and Safety in ICT",
      "ICT in Everyday Life",
    ],
  },
  {
    subject: "RME",
    topics: [
      "God as Creator",
      "Moral Teachings in Religion",
      "Prayer and Worship",
      "The Ten Commandments",
      "Festivals and Religious Celebrations",
      "Good Morals and Values",
      "Authority and Obedience",
      "Honesty and Truthfulness",
      "Tolerance and Peaceful Co-existence",
      "Work and Leisure",
    ],
  },
  {
    subject: "French",
    topics: [
      "Greetings and Introductions",
      "Family and Relationships",
      "Daily Routine and Time",
      "Food and Drinks",
      "School Life",
      "Parts of the Body and Health",
      "Weather and Seasons",
      "Directions and Transportation",
      "Shopping and Money",
      "Professions and Occupations",
    ],
  },
  {
    subject: "Creative Arts",
    topics: [
      "Elements and Principles of Design",
      "Drawing and Painting",
      "Textiles and Fabric Design",
      "Pottery and Ceramics",
      "Music and Dance",
      "Drama and Theatre",
      "Ghanaian Art Forms",
      "Colour Theory",
      "Printmaking",
      "Art Appreciation and Criticism",
    ],
  },
  {
    subject: "Career Technology",
    topics: [
      "Woodwork and Carpentry",
      "Metalwork Basics",
      "Technical Drawing",
      "Sewing and Textiles",
      "Food and Nutrition",
      "Agriculture and Farming",
      "Entrepreneurship",
      "Safety in the Workshop",
      "Tools and Equipment",
      "Career Opportunities in Technology",
    ],
  },
];

export const SHS_SYLLABUS: SyllabusTopic[] = [
  {
    subject: "Core Mathematics",
    topics: [
      "Sets and Operations on Sets",
      "Real Number System",
      "Algebraic Expressions and Equations",
      "Surds",
      "Quadratic Equations and Functions",
      "Indices and Logarithms",
      "Sequences and Series",
      "Matrices and Determinants",
      "Trigonometry (Sine, Cosine, Tangent Rules)",
      "Mensuration (Areas and Volumes)",
      "Coordinate Geometry",
      "Statistics (Mean, Median, Mode, Standard Deviation)",
      "Probability",
      "Vectors in Two Dimensions",
      "Linear and Quadratic Inequalities",
    ],
  },
  {
    subject: "English Language",
    topics: [
      "Comprehension (Prose and Poetry)",
      "Summary Writing",
      "Continuous Writing (Essays, Letters, Articles, Reports)",
      "Lexis and Structure",
      "Idioms, Phrasal Verbs and Collocations",
      "Vocabulary in Context",
      "Clauses and Complex Sentences",
      "Active and Passive Voice",
      "Concord and Agreement",
      "Registers and Formal/Informal Language",
      "Oral English (Vowels, Consonants, Stress and Intonation)",
      "Literary Appreciation",
    ],
  },
  {
    subject: "Integrated Science",
    topics: [
      "Scientific Method and Measurement",
      "Classification of Living Things",
      "Cell Biology and Organisation of Life",
      "Ecology and Environment",
      "Genetics and Heredity",
      "Evolution and Adaptation",
      "Atomic Structure and Chemical Bonding",
      "Acids, Bases and Salts",
      "Energy Transformations",
      "Electricity and Electromagnetism",
      "Waves and Light",
      "Agricultural Science Basics",
    ],
  },
  {
    subject: "Social Studies",
    topics: [
      "The Ghanaian Social Structure",
      "Governance and Political Systems",
      "The 1992 Constitution",
      "Human Rights and Responsibilities",
      "Economic Development in Ghana",
      "Globalisation and Its Effects",
      "Science, Technology and Society",
      "Population Growth and Urbanisation",
      "Environmental Degradation and Sustainability",
      "Conflict and Conflict Resolution",
      "Culture, Identity and Tourism",
      "Youth Empowerment and National Development",
    ],
  },
  {
    subject: "Physics",
    topics: [
      "Measurements and Units",
      "Kinematics (Motion in One and Two Dimensions)",
      "Dynamics (Newton's Laws of Motion)",
      "Work, Energy and Power",
      "Waves and Sound",
      "Light and Optics",
      "Heat and Thermodynamics",
      "Electricity (Current, Resistance, Circuits)",
      "Electromagnetism",
      "Atomic and Nuclear Physics",
      "Gravitational Field",
      "Projectile Motion",
    ],
  },
  {
    subject: "Chemistry",
    topics: [
      "Atomic Structure and Periodic Table",
      "Chemical Bonding",
      "States of Matter and Gas Laws",
      "Stoichiometry and Chemical Equations",
      "Acids, Bases and Salts",
      "Redox Reactions and Electrochemistry",
      "Organic Chemistry (Alkanes, Alkenes, Alkynes)",
      "Rates of Chemical Reactions",
      "Chemical Equilibrium",
      "Energy Changes in Reactions",
      "Metals and Their Compounds",
      "Environmental Chemistry",
    ],
  },
  {
    subject: "Biology",
    topics: [
      "Cell Structure and Organisation",
      "Nutrition in Plants and Animals",
      "Transport in Living Things",
      "Respiration and Gaseous Exchange",
      "Excretion",
      "Reproduction in Plants and Animals",
      "Growth and Development",
      "Ecology (Ecosystem, Food Chains, Nutrient Cycles)",
      "Genetics and Heredity",
      "Evolution and Natural Selection",
      "Diseases and Immunology",
      "Biotechnology",
    ],
  },
  {
    subject: "Economics",
    topics: [
      "Basic Economic Concepts (Scarcity, Choice, Opportunity Cost)",
      "Demand and Supply",
      "Theory of Production and Costs",
      "Market Structures",
      "National Income and GDP",
      "Money and Banking",
      "Inflation and Unemployment",
      "International Trade",
      "Government Fiscal and Monetary Policy",
      "Economic Development in West Africa",
      "Agriculture and Industry in Ghana",
    ],
  },
  {
    subject: "Geography",
    topics: [
      "Map Reading and Interpretation",
      "Physical Geography (Rocks, Weathering, Landforms)",
      "Climate and Vegetation of West Africa",
      "Rivers and Drainage Systems",
      "Population Studies",
      "Urbanisation and Settlement",
      "Agriculture and Food Production",
      "Mining and Manufacturing Industries",
      "Environmental Problems and Management",
      "Transport and Communication",
    ],
  },
  {
    subject: "Government",
    topics: [
      "Meaning and Types of Government",
      "Arms of Government (Executive, Legislature, Judiciary)",
      "Democracy and Dictatorship",
      "Political Parties and Pressure Groups",
      "The Electoral Process",
      "The 1992 Constitution of Ghana",
      "Local Government in Ghana",
      "Public Administration and Civil Service",
      "International Organisations (UN, AU, ECOWAS)",
      "Human Rights and the Rule of Law",
    ],
  },
  {
    subject: "Literature",
    topics: [
      "Introduction to Literary Terms",
      "Poetry Analysis (Themes, Imagery, Tone)",
      "Prose Fiction (Plot, Characters, Setting, Theme)",
      "Drama (Tragedy, Comedy, Stage Directions)",
      "African Literature",
      "Figures of Speech",
      "Narrative Techniques",
      "Social Criticism in Literature",
      "Symbolism and Allegory",
      "Set Texts and Unseen Passages",
    ],
  },
  {
    subject: "Elective Mathematics",
    topics: [
      "Coordinate Geometry (Advanced)",
      "Differentiation and Its Applications",
      "Integration",
      "Trigonometric Functions and Equations",
      "Complex Numbers",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Vectors (2D and 3D)",
      "Dynamics and Statics",
      "Regression and Correlation",
      "Mathematical Induction",
    ],
  },
  {
    subject: "Accounting",
    topics: [
      "Introduction to Accounting",
      "Double Entry Bookkeeping",
      "Trial Balance",
      "Trading, Profit and Loss Account",
      "Balance Sheet",
      "Bank Reconciliation",
      "Depreciation of Fixed Assets",
      "Control Accounts",
      "Partnership Accounts",
      "Manufacturing Accounts",
      "Financial Statements of Companies",
    ],
  },
];

export function getSyllabus(level: "JHS" | "SHS"): SyllabusTopic[] {
  return level === "JHS" ? JHS_SYLLABUS : SHS_SYLLABUS;
}

export function getTopicsForSubject(level: "JHS" | "SHS", subject: string): string[] {
  const syllabus = getSyllabus(level);
  const entry = syllabus.find(
    (s) => s.subject.toLowerCase() === subject.toLowerCase()
  );
  return entry?.topics ?? [];
}
